Repository nakamura0907/Walkly, pull requests merged in 2021-06, with the labels that each got.

#3 規約書反映
  .idea/vcs.xml
  docs/convention/README.md
  docs/convention/coding-convention.md
  docs/convention/dev-cycle.md
  docs/convention/git.md
  docs/convention/naming-convention.md
  docs/convention/word.md
  docs/dev/README.md
Labels: documentation

#7 タイトルバー非表示 #5
  app/src/main/res/values/themes.xml
Labels: enhancement

#8 git規約の作成 #6
  .idea/gradle.xml
  docs/convention/git.md
  docs/convention/word.md
Labels: documentation

#4 Kotlinコーディング規約の作成
  docs/convention/README.md
  docs/convention/coding-convention.md
  docs/convention/naming-convention.md
Labels: documentation

#17 現在地取得
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/walky/MapsActivity.kt
Labels: enhancement

#19 アイコン設定 -> master
  .idea/.name
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/misc.xml
  app/src/main/res/drawable/walkly_icon_background.xml
  app/src/main/res/mipmap-anydpi-v26/walkly_icon.xml
  app/src/main/res/mipmap-anydpi-v26/walkly_icon_round.xml
  app/src/main/res/values/strings.xml
  app/src/main/walkly_icon-playstore.png
Labels: enhancement

#20 リファクタリング
  app/src/androidTest/java/com/example/walkly/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/walkly/MapsActivity.kt
  app/src/main/java/com/example/walkly/application/MapApplicationService.kt
  app/src/main/java/com/example/walkly/domain/model/GPS.kt
  app/src/main/java/com/example/walkly/domain/model/MyMap.kt
  app/src/main/java/com/example/walkly/domain/repository/IUserRepository.kt
  app/src/main/java/com/example/walkly/infrastructure/UserRepository.kt
  app/src/main/java/com/example/walkly/ui/MapCallback.kt
  app/src/main/java/com/example/walky/MapsActivity.kt
  app/src/test/java/com/example/walkly/ExampleUnitTest.kt
  docs/convention/coding-convention.md
  docs/dev/Feature/F02/001/class-diagram.png
  docs/dev/Feature/F02/001/class-diagram.pu
  docs/dev/Feature/F02/001/sequence-diagram.png
  docs/dev/Feature/F02/001/sequence-diagram.pu
  docs/dev/Feature/F02/001/設計書.md
Labels: documentation, enhancement

#21 アイコンエラー修正
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/walkly_icon.png
  app/src/main/res/mipmap-hdpi/walkly_icon_foreground.png
  app/src/main/res/mipmap-hdpi/walkly_icon_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/walkly_icon.png
  app/src/main/res/mipmap-mdpi/walkly_icon_foreground.png
  app/src/main/res/mipmap-mdpi/walkly_icon_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/walkly_icon.png
  app/src/main/res/mipmap-xhdpi/walkly_icon_foreground.png
  app/src/main/res/mipmap-xhdpi/walkly_icon_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/walkly_icon.png
  app/src/main/res/mipmap-xxhdpi/walkly_icon_foreground.png
  app/src/main/res/mipmap-xxhdpi/walkly_icon_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/walkly_icon.png
  app/src/main/res/mipmap-xxxhdpi/walkly_icon_foreground.png
  app/src/main/res/mipmap-xxxhdpi/walkly_icon_round.png
Labels: bug, enhancement

#25 アイコンの背景色を変更
  app/src/main/res/drawable/walkly_icon_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-anydpi-v26/walkly_icon.xml
  app/src/main/res/mipmap-anydpi-v26/walkly_icon_round.xml
  app/src/main/res/mipmap-hdpi/walkly_icon.png
  app/src/main/res/mipmap-hdpi/walkly_icon_round.png
  app/src/main/res/mipmap-mdpi/walkly_icon.png
  app/src/main/res/mipmap-mdpi/walkly_icon_round.png
  app/src/main/res/mipmap-xhdpi/walkly_icon.png
  app/src/main/res/mipmap-xhdpi/walkly_icon_round.png
  app/src/main/res/mipmap-xxhdpi/walkly_icon.png
  app/src/main/res/mipmap-xxhdpi/walkly_icon_round.png
  app/src/main/res/mipmap-xxxhdpi/walkly_icon.png
  app/src/main/res/mipmap-xxxhdpi/walkly_icon_round.png
  app/src/main/res/values/walkly_icon_background.xml
  app/src/main/walkly_icon-playstore.png
Labels: bug

#27 初回起動時の強制終了問題修正
  app/src/main/java/com/example/walkly/MapsActivity.kt
  app/src/main/java/com/example/walkly/domain/model/GPS.kt
  app/src/main/res/values/strings.xml
Labels: bug

#29 レイアウトが重なってしまう問題修正
  app/src/main/res/layout/activity_maps.xml
Labels: bug

#34 スプラッシュスクリーンの実装 #24
  .idea/gradle.xml
  app/build.gradle
  app/build.gradle.rej
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/walkly/SplashActivity.kt
  app/src/main/res/drawable/splash.png
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#37 ボトムボタン修正#31
  app/src/main/java/com/example/walkly/MapsActivity.kt
  app/src/main/res/layout/activity_maps.xml
Labels: bug

#38 ボトムボタン微調整 #31
  app/src/main/res/layout/activity_maps.xml
Labels: bug

#39 チェックポイント表示の設計
  docs/dev/Feature/F02/002/class-diagram.png
  docs/dev/Feature/F02/002/class-diagram.pu
  docs/dev/Feature/F02/002/sequence-diagram.png
  docs/dev/Feature/F02/002/sequence-diagram.pu
  docs/dev/Feature/F02/002/チェックポイント.md
  docs/dev/Feature/F02/010/class-diagram.png
  docs/dev/Feature/F02/010/class-diagram.pu
  docs/dev/Feature/F02/010/sequence-diagram.png
  docs/dev/Feature/F02/010/sequence-diagram.pu
  docs/dev/Feature/F02/010/天候予想.md
Labels: documentation

#42 パーミッション挙動変更
  app/src/main/java/com/example/walkly/SplashActivity.kt
  app/src/main/java/com/example/walkly/domain/model/GPS.kt
  app/src/main/java/com/example/walkly/lib/Permission.kt
  app/src/main/java/com/example/walkly/ui/PermissionCallback.kt
  app/src/main/res/values/permission.xml
Labels: bug, enhancement

#44 ズームボタン削除#31
  app/src/main/java/com/example/walkly/ui/MapCallback.kt
Labels: bug

#49 施設クリックでチェックポイント
  .idea/misc.xml
  app/src/main/java/com/example/walkly/application/MapApplicationService.kt
  app/src/main/java/com/example/walkly/domain/model/MyMap.kt
  app/src/main/java/com/example/walkly/domain/model/mymap/MarkerList.kt
  app/src/main/java/com/example/walkly/domain/model/mymap/MyMap.kt
  app/src/main/java/com/example/walkly/ui/MapCallback.kt
Labels: enhancement
